// ============ PARKING DATA ============
let parkingData = JSON.parse(localStorage.getItem('parkingData')) || [
    {
        id: 1,
    name: 'Градски гараж (ул. Славянска)',
        location: 'ул. Славянска, 2',
        totalSpots: 120,
        availableSpots: 45,
        price: '3.50 BGN/час',
        rating: 4.5,
        reviews: 128,
        description: 'Модерен паркинг близо до центъра, с видеонаблюдение и охрана.',
        coordinates: { lat: 42.5145, lng: 27.4615 },
        amenities: ['Видеонаблюдение', 'Охрана 24/7', 'Възлични'], status: 'available'
    },
    {
        id: 2,
    name: 'Централен гараж (Бургас център)',
        location: 'Бургас Център',
        totalSpots: 250,
        availableSpots: 5,
        price: '5.00 BGN/час',
        rating: 4.2,
        reviews: 256,
        description: 'Най-голямата паркинг площадка в центъра на Бургас.',
        coordinates: { lat: 42.5038, lng: 27.4626 },
        amenities: ['Лифт', 'Достъп за инвалиди', 'Охрана'], status: 'full'
,
    // User-added parking entries (IDs 4001 - 4045)
    {
        id: 4001,
        name: 'Паркинг "Гурко"',
        location: 'ул. "Гурко"',
        totalSpots: 80,
        availableSpots: 18,
        price: '3.00 BGN/час',
        rating: 4.1,
        reviews: 42,
        description: 'Паркинг в близост до ул. Гурко.',
        coordinates: { lat: 42.4989, lng: 27.4683 },
        amenities: ['Осветление', 'Паркомати'], status: 'available'
    },
    {
        id: 4002,
        name: 'Паркинг "Опера"',
        location: 'около Операта',
        totalSpots: 60,
        availableSpots: 12,
        price: '3.50 BGN/час',
        rating: 4.4,
        reviews: 88,
        description: 'Паркинг за посетители на оперния театър.',
        coordinates: { lat: 42.4990, lng: 27.4684 },
        amenities: ['Осветление'], status: 'available'
    },
    {
        id: 4003,
        name: 'Паркинг "БСУ" (до Бургаски свободен университет)',
        location: 'до БСУ',
        totalSpots: 120,
        availableSpots: 30,
        price: '2.80 BGN/час',
        rating: 4.0,
        reviews: 60,
        description: 'Паркинг близо до Бургаския свободен университет.',
        coordinates: { lat: 42.4991, lng: 27.4685 },
        amenities: ['Достъп за инвалиди', 'Паркомати'], status: 'available'
    },
    {
        id: 4004,
        name: 'Паркинг к-с "Славейков" (до ВХТИ)',
        location: 'ж.к. Славейков / ВХТИ',
        totalSpots: 90,
        availableSpots: 14,
        price: '3.20 BGN/час',
        rating: 3.9,
        reviews: 34,
        description: 'Квартален паркинг в района на ВХТИ.',
        coordinates: { lat: 42.4992, lng: 27.4686 },
        amenities: ['Осветление'], status: 'available'
    },
    {
        id: 4005,
        name: 'Паркинг "Изгрев бл. 7"',
        location: 'ж.к. Изгрев, бл. 7',
        totalSpots: 40,
        availableSpots: 8,
        price: '2.50 BGN/час',
        rating: 3.6,
        reviews: 12,
        description: 'Квартален паркинг до бл. 7 в Изгрев.',
        coordinates: { lat: 42.4993, lng: 27.4687 },
        amenities: ['Осветление'], status: 'available'
    },
    {
        id: 4006,
        name: 'Паркинг "Пиргос" (ж.к. Лазур)',
        location: 'ж.к. Лазур',
        totalSpots: 70,
        availableSpots: 20,
        price: '3.80 BGN/час',
        rating: 4.2,
        reviews: 48,
        description: 'Паркинг в зоната на Лазур, близо до Пиргос.',
        coordinates: { lat: 42.4994, lng: 27.4688 },
        amenities: ['Паркомати', 'Осветление'], status: 'available'
    },
    {
        id: 4007,
        name: 'Паркинг "Културно-образователен център" (ул. Средна гора)',
        location: 'ул. Средна гора',
        totalSpots: 55,
        availableSpots: 10,
        price: '3.00 BGN/час',
        rating: 4.0,
        reviews: 22,
        description: 'Паркинг до Културно-образователния център.',
        coordinates: { lat: 42.4995, lng: 27.4689 },
        amenities: ['Осветление'], status: 'available'
    },
    {
        id: 4008,
        name: 'Паркинг "ИХ България" (ул. България)',
        location: 'ул. България',
        totalSpots: 85,
        availableSpots: 26,
        price: '3.50 BGN/час',
        rating: 4.1,
        reviews: 36,
        description: 'Паркинг до ИХ България, удобно за служители и посетители.',
        coordinates: { lat: 42.4996, lng: 27.4690 },
        amenities: ['Паркомати'], status: 'available'
    },
    {
        id: 4009,
        name: 'Паркинг Burgas Plaza (клиентски)',
        location: 'Burgas Plaza',
        totalSpots: 200,
        availableSpots: 60,
        price: '4.00 BGN/час',
        rating: 4.3,
        reviews: 210,
        description: 'Клиентски паркинг на Burgas Plaza.',
        coordinates: { lat: 42.4997, lng: 27.4691 },
        amenities: ['Лифт', 'Паркомати'], status: 'available'
    },
    {
        id: 4010,
        name: 'Паркинг Mr. Bricolage (клиентски)',
        location: 'Mr. Bricolage зона',
        totalSpots: 150,
        availableSpots: 40,
        price: '3.50 BGN/час',
        rating: 4.0,
        reviews: 98,
        description: 'Клиентски паркинг на Mr. Bricolage.',
        coordinates: { lat: 42.4998, lng: 27.4692 },
        amenities: ['Паркомати'], status: 'available'
    },
    {
        id: 4011,
        name: 'Паркинг Морска гара',
        location: 'Морска гара',
        totalSpots: 120,
        availableSpots: 20,
        price: '4.00 BGN/час',
        rating: 4.2,
        reviews: 132,
        description: 'Паркинг при Морската гара.',
        coordinates: { lat: 42.4999, lng: 27.4693 },
        amenities: ['Охрана'], status: 'available'
    },
    {
        id: 4012,
        name: 'Паркинг Пристанище Бургас – зона за посетители',
        location: 'Пристанище Бургас',
        totalSpots: 140,
        availableSpots: 40,
        price: '4.50 BGN/час',
        rating: 4.1,
        reviews: 75,
        description: 'Зона за посетители на пристанището.',
        coordinates: { lat: 42.5000, lng: 27.4694 },
        amenities: ['Осветление'], status: 'available'
    },
    {
        id: 4013,
        name: 'Паркинг "Магазия 1"',
        location: 'Магазия 1',
        totalSpots: 60,
        availableSpots: 10,
        price: '3.00 BGN/час',
        rating: 3.8,
        reviews: 18,
        description: 'Паркинг до Магазия 1.',
        coordinates: { lat: 42.5001, lng: 27.4695 },
        amenities: ['Паркомати'], status: 'available'
    },
    {
        id: 4014,
        name: 'Паркинг Централна автогара "Юг"',
        location: 'Централна автогара – юг',
        totalSpots: 160,
        availableSpots: 22,
        price: '3.20 BGN/час',
        rating: 3.9,
        reviews: 44,
        description: 'Паркинг при централната автогара (юг).',
        coordinates: { lat: 42.5002, lng: 27.4696 },
        amenities: ['WC', 'Осветление'], status: 'available'
    },
    {
        id: 4015,
        name: 'Паркинг Централна жп гара',
        location: 'Централна жп гара',
        totalSpots: 200,
        availableSpots: 12,
        price: '3.80 BGN/час',
        rating: 4.0,
        reviews: 150,
        description: 'Паркинг в района на централната жп гара.',
        coordinates: { lat: 42.5003, lng: 27.4697 },
        amenities: ['WC', 'Осветление'], status: 'available'
    },
    {
        id: 4016,
        name: 'Паркинг "Морска градина – Казино"',
        location: 'Морска градина – Казино',
        totalSpots: 120,
        availableSpots: 30,
        price: '4.00 BGN/час',
        rating: 4.3,
        reviews: 98,
        description: 'Паркинг в зоната на Морското казино.',
        coordinates: { lat: 42.5004, lng: 27.4698 },
        amenities: ['Подземен', 'Охрана'], status: 'available'
    },
    {
        id: 4017,
        name: 'Паркинг "Морска градина – Флора"',
        location: 'Морска градина – Флора',
        totalSpots: 90,
        availableSpots: 20,
        price: '3.50 BGN/час',
        rating: 4.2,
        reviews: 64,
        description: 'Паркинг до зоната Флора в Морската градина.',
        coordinates: { lat: 42.5005, lng: 27.4699 },
        amenities: ['Осветление'], status: 'available'
    },
    {
        id: 4018,
        name: 'Паркинг "Морска градина – Терасата"',
        location: 'Морска градина – Терасата',
        totalSpots: 95,
        availableSpots: 18,
        price: '3.50 BGN/час',
        rating: 4.1,
        reviews: 70,
        description: 'Паркинг в близост до Терасата в Морската градина.',
        coordinates: { lat: 42.5006, lng: 27.4700 },
        amenities: ['Паркомати'], status: 'available'
    },
    {
        id: 4019,
        name: 'Паркинг "Морска градина – Пантеона"',
        location: 'Морска градина – Пантеона',
        totalSpots: 80,
        availableSpots: 16,
        price: '3.20 BGN/час',
        rating: 4.0,
        reviews: 48,
        description: 'Паркинг до Пантеона в Морската градина.',
        coordinates: { lat: 42.5007, lng: 27.4701 },
        amenities: ['Осветление'], status: 'available'
    },
    {
        id: 4020,
        name: 'Паркинг "Морска градина – Езеро"',
        location: 'Морска градина – Езеро',
        totalSpots: 70,
        availableSpots: 14,
        price: '3.00 BGN/час',
        rating: 4.1,
        reviews: 36,
        description: 'Паркинг край езерото в Морската градина.',
        coordinates: { lat: 42.5008, lng: 27.4702 },
        amenities: ['Осветление'], status: 'available'
    },
    {
        id: 4021,
        name: 'Паркинг "Морска градина – Капаните"',
        location: 'Морска градина – Капаните',
        totalSpots: 60,
        availableSpots: 10,
        price: '3.00 BGN/час',
        rating: 3.9,
        reviews: 22,
        description: 'Паркинг в района на Капаните.',
        coordinates: { lat: 42.5009, lng: 27.4703 },
        amenities: ['Паркомати'], status: 'available'
    },
    {
        id: 4022,
        name: 'Паркинг "Морска градина – Транспортна болница"',
        location: 'Морска градина – Транспортна болница',
        totalSpots: 50,
        availableSpots: 8,
        price: '2.80 BGN/час',
        rating: 3.8,
        reviews: 15,
        description: 'Паркинг в близост до транспортната болница.',
        coordinates: { lat: 42.5010, lng: 27.4704 },
        amenities: ['Осветление'], status: 'available'
    },
    {
        id: 4023,
        name: 'Паркинг "Морска градина – Бункера"',
        location: 'Морска градина – Бункера',
        totalSpots: 40,
        availableSpots: 6,
        price: '2.50 BGN/час',
        rating: 3.6,
        reviews: 10,
        description: 'Малък паркинг в района на Бункера.',
        coordinates: { lat: 42.5011, lng: 27.4705 },
        amenities: ['Осветление'], status: 'available'
    },
    {
        id: 4024,
        name: 'Паркинг "Морска градина – Летен театър"',
        location: 'Морска градина – Летен театър',
        totalSpots: 110,
        availableSpots: 28,
        price: '3.80 BGN/час',
        rating: 4.2,
        reviews: 95,
        description: 'Паркинг до Летен театър.',
        coordinates: { lat: 42.5012, lng: 27.4706 },
        amenities: ['Осветление', 'Паркомати'], status: 'available'
    },
    {
        id: 4025,
        name: 'Паркинг "Морска градина – Парк Арена ОЗК"',
        location: 'Парк Арена ОЗК',
        totalSpots: 220,
        availableSpots: 60,
        price: '4.50 BGN/час',
        rating: 4.4,
        reviews: 220,
        description: 'Голям паркинг при Парк Арена ОЗК.',
        coordinates: { lat: 42.5013, lng: 27.4707 },
        amenities: ['Паркомати', 'Охрана'], status: 'available'
    },
    {
        id: 4026,
        name: 'Паркинг "Парк Арена ОЗК – север"',
        location: 'Парк Арена ОЗК – север',
        totalSpots: 110,
        availableSpots: 30,
        price: '4.00 BGN/час',
        rating: 4.2,
        reviews: 88,
        description: 'Северна зона на паркинга при Арена ОЗК.',
        coordinates: { lat: 42.5014, lng: 27.4708 },
        amenities: ['Осветление'], status: 'available'
    },
    {
        id: 4027,
        name: 'Паркинг "Парк Арена ОЗК – юг"',
        location: 'Парк Арена ОЗК – юг',
        totalSpots: 110,
        availableSpots: 22,
        price: '4.00 BGN/час',
        rating: 4.1,
        reviews: 74,
        description: 'Южна зона на паркинга при Арена ОЗК.',
        coordinates: { lat: 42.5015, lng: 27.4709 },
        amenities: ['Осветление'], status: 'available'
    },
    {
        id: 4028,
        name: 'Паркинг "Мол Галерия Бургас"',
        location: 'Мол Галерия Бургас',
        totalSpots: 300,
        availableSpots: 95,
        price: '4.50 BGN/час',
        rating: 4.3,
        reviews: 340,
        description: 'Голям паркинг при Мол Галерия.',
        coordinates: { lat: 42.5016, lng: 27.4710 },
        amenities: ['Лифт', 'Паркомати'], status: 'available'
    },
    {
        id: 4029,
        name: 'Паркинг "Кауфланд – Славейков"',
        location: 'Кауфланд Славейков',
        totalSpots: 180,
        availableSpots: 40,
        price: '3.80 BGN/час',
        rating: 4.0,
        reviews: 190,
        description: 'Паркинг при Кауфланд в Славейков.',
        coordinates: { lat: 42.5017, lng: 27.4711 },
        amenities: ['Паркомати'], status: 'available'
    },
    {
        id: 4030,
        name: 'Паркинг "Кауфланд – Изгрев"',
        location: 'Кауфланд Изгрев',
        totalSpots: 160,
        availableSpots: 36,
        price: '3.80 BGN/час',
        rating: 4.0,
        reviews: 132,
        description: 'Паркинг при Кауфланд в Изгрев.',
        coordinates: { lat: 42.5018, lng: 27.4712 },
        amenities: ['Паркомати'], status: 'available'
    },
    {
        id: 4031,
        name: 'Паркинг "Лидл – Славейков"',
        location: 'Лидл Славейков',
        totalSpots: 120,
        availableSpots: 28,
        price: '3.20 BGN/час',
        rating: 3.9,
        reviews: 88,
        description: 'Паркинг при Лидл в Славейков.',
        coordinates: { lat: 42.5019, lng: 27.4713 },
        amenities: ['Паркомати'], status: 'available'
    },
    {
        id: 4032,
        name: 'Паркинг "Лидл – Меден рудник"',
        location: 'Лидл Меден рудник',
        totalSpots: 140,
        availableSpots: 50,
        price: '3.00 BGN/час',
        rating: 3.8,
        reviews: 64,
        description: 'Паркинг при Лидл в Меден рудник.',
        coordinates: { lat: 42.5020, lng: 27.4714 },
        amenities: ['Паркомати'], status: 'available'
    },
    {
        id: 4033,
        name: 'Паркинг "Лидл – Изгрев"',
        location: 'Лидл Изгрев',
        totalSpots: 110,
        availableSpots: 26,
        price: '3.20 BGN/час',
        rating: 3.9,
        reviews: 40,
        description: 'Паркинг при Лидл в Изгрев.',
        coordinates: { lat: 42.5021, lng: 27.4715 },
        amenities: ['Паркомати'], status: 'available'
    },
    {
        id: 4034,
        name: 'Паркинг "Билла – Славейков"',
        location: 'Билла Славейков',
        totalSpots: 90,
        availableSpots: 18,
        price: '3.00 BGN/час',
        rating: 3.8,
        reviews: 30,
        description: 'Паркинг при Билла в Славейков.',
        coordinates: { lat: 42.5022, lng: 27.4716 },
        amenities: ['Паркомати'], status: 'available'
    },
    {
        id: 4035,
        name: 'Паркинг "Билла – Център"',
        location: 'Билла Център',
        totalSpots: 100,
        availableSpots: 20,
        price: '3.50 BGN/час',
        rating: 4.0,
        reviews: 52,
        description: 'Паркинг при Билла в центъра.',
        coordinates: { lat: 42.5023, lng: 27.4717 },
        amenities: ['Паркомати'], status: 'available'
    },
    {
        id: 4036,
        name: 'Паркинг "Билла – Меден рудник"',
        location: 'Билла Меден рудник',
        totalSpots: 80,
        availableSpots: 22,
        price: '3.00 BGN/час',
        rating: 3.7,
        reviews: 18,
        description: 'Паркинг при Билла в Меден рудник.',
        coordinates: { lat: 42.5024, lng: 27.4718 },
        amenities: ['Паркомати'], status: 'available'
    },
    {
        id: 4037,
        name: 'Паркинг "Технополис – Славейков"',
        location: 'Технополис Славейков',
        totalSpots: 160,
        availableSpots: 48,
        price: '3.80 BGN/час',
        rating: 4.1,
        reviews: 120,
        description: 'Паркинг при Технополис в Славейков.',
        coordinates: { lat: 42.5025, lng: 27.4719 },
        amenities: ['Паркомати'], status: 'available'
    },
    {
        id: 4038,
        name: 'Паркинг "Техномаркет – Славейков"',
        location: 'Техномаркет Славейков',
        totalSpots: 120,
        availableSpots: 30,
        price: '3.50 BGN/час',
        rating: 4.0,
        reviews: 74,
        description: 'Паркинг при Техномаркет в Славейков.',
        coordinates: { lat: 42.5026, lng: 27.4720 },
        amenities: ['Паркомати'], status: 'available'
    },
    {
        id: 4039,
        name: 'Паркинг "Декатлон Бургас"',
        location: 'Декатлон зона',
        totalSpots: 250,
        availableSpots: 80,
        price: '4.00 BGN/час',
        rating: 4.2,
        reviews: 200,
        description: 'Голям паркинг при Декатлон.',
        coordinates: { lat: 42.5027, lng: 27.4721 },
        amenities: ['Паркомати', 'Осветление'], status: 'available'
    },
    {
        id: 4040,
        name: 'Паркинг "Метро Бургас"',
        location: 'Метро зона',
        totalSpots: 300,
        availableSpots: 120,
        price: '4.50 BGN/час',
        rating: 4.3,
        reviews: 240,
        description: 'Голям търговски паркинг при Метро.',
        coordinates: { lat: 42.5028, lng: 27.4722 },
        amenities: ['Паркомати', 'Охрана'], status: 'available'
    },
    {
        id: 4041,
        name: 'Паркинг "Практикер Бургас"',
        location: 'Практикер зона',
        totalSpots: 180,
        availableSpots: 50,
        price: '3.80 BGN/час',
        rating: 4.0,
        reviews: 130,
        description: 'Паркинг при Практикер.',
        coordinates: { lat: 42.5029, lng: 27.4723 },
        amenities: ['Паркомати'], status: 'available'
    },
    {
        id: 4042,
        name: 'Паркинг "Триа Сити Център"',
        location: 'Триа Сити Център',
        totalSpots: 260,
        availableSpots: 90,
        price: '4.20 BGN/час',
        rating: 4.3,
        reviews: 210,
        description: 'Голям паркинг при Триа Сити Център.',
        coordinates: { lat: 42.5030, lng: 27.4724 },
        amenities: ['Лифт', 'Паркомати'], status: 'available'
    },
    {
        id: 4043,
        name: 'Паркинг "Супермаркет Болеро – Лазур"',
        location: 'Болеро Лазур',
        totalSpots: 70,
        availableSpots: 18,
        price: '3.00 BGN/час',
        rating: 3.9,
        reviews: 26,
        description: 'Паркинг при супермаркет Болеро в Лазур.',
        coordinates: { lat: 42.5031, lng: 27.4725 },
        amenities: ['Паркомати'], status: 'available'
    },
    {
        id: 4044,
        name: 'Паркинг "Супермаркет Болеро – Славейков"',
        location: 'Болеро Славейков',
        totalSpots: 80,
        availableSpots: 20,
        price: '3.00 BGN/час',
        rating: 3.9,
        reviews: 30,
        description: 'Паркинг при супермаркет Болеро в Славейков.',
        coordinates: { lat: 42.5032, lng: 27.4726 },
        amenities: ['Паркомати'], status: 'available'
    },
    {
        id: 4045,
        name: 'Паркинг "Супермаркет Болеро – Център"',
        location: 'Болеро Център',
        totalSpots: 90,
        availableSpots: 25,
        price: '3.20 BGN/час',
        rating: 4.0,
        reviews: 38,
        description: 'Паркинг при супермаркет Болеро в центъра.',
        coordinates: { lat: 42.5033, lng: 27.4727 },
        amenities: ['Паркомати'], status: 'available'
    }
];
    {
        id: 3,
    name: 'Изгрев Парк (ж.к. Изгрев)',
        location: 'кв. Изгрев',
        totalSpots: 180,
        availableSpots: 60,
        price: '4.00 BGN/час',
        rating: 4.0,
        reviews: 192,
        description: 'Голям паркинг в кв. Изгрев със сенчести дървета.',
        coordinates: { lat: 42.5000, lng: 27.4670 },
        amenities: ['Видеонаблюдение', 'WC'], status: 'available'
    },
    {
        id: 4,
    name: 'Южен гараж (бул. Митрополит Методи Кусев)',
        location: 'бул. "Митрополит Методи Кусев" 12',
        totalSpots: 100,
        availableSpots: 20,
        price: '3.00 BGN/час',
        rating: 3.8,
        reviews: 89,
        description: 'Нискоценов паркинг на южния булевард.',
        coordinates: { lat: 42.4940, lng: 27.4540 },
        amenities: ['Охрана'], status: 'available'
    },
    {
        id: 5,
    name: 'Западна зона (ул. Черни връх)',
        location: 'ул. "Черни връх" 5',
        totalSpots: 75,
        availableSpots: 0,
        price: '2.50 BGN/час',
        rating: 3.5,
        reviews: 47,
        description: 'Компактен паркинг в западния район, често зает.',
        coordinates: { lat: 42.5080, lng: 27.4500 },
        amenities: ['Паркомати'], status: 'full'
    },
    {
        id: 6,
    name: 'Източна зона (ул. Източна)',
        location: 'ул. "Източна" 22',
        totalSpots: 130,
        availableSpots: 90,
        price: '4.50 BGN/час',
        rating: 4.7,
        reviews: 210,
        description: 'Чист, добре охраняван паркинг в източната част на града.',
        coordinates: { lat: 42.5170, lng: 27.4730 },
        amenities: ['Видеонаблюдение', 'Зарядна станция'], status: 'available'
    },
    {
        id: 7,
    name: 'Младост (ж.к. Младост)',
        location: 'ж.к. "Младост" 3',
        totalSpots: 90,
        availableSpots: 10,
        price: '3.20 BGN/час',
        rating: 4.1,
        reviews: 101,
        description: 'Паркинг в жилищен комплекс, идеален за жители.',
        coordinates: { lat: 42.5210, lng: 27.4800 },
        amenities: ['Достъп за инвалиди'], status: 'available'
    },
    {
        id: 8,
    name: 'До болница (бул. Демокрация)',
        location: 'бул. "Демокрация" 30',
        totalSpots: 140,
        availableSpots: 30,
        price: '5.50 BGN/час',
        rating: 4.9,
        reviews: 340,
        description: 'Паркинг до болницата, удобен за пациенти и посетители.',
        coordinates: { lat: 42.5270, lng: 27.4900 },
        amenities: ['Охрана 24/7', 'WC'], status: 'available'
    },
    {
        id: 9,
    name: 'Лазур (ул. Пирин)',
        location: 'ул. "Пирин" 18',
        totalSpots: 200,
        availableSpots: 150,
        price: '6.00 BGN/час',
        rating: 4.6,
        reviews: 275,
        description: 'Луксозен паркинг с климатизация и охрана.',
        coordinates: { lat: 42.5300, lng: 27.4980 },
        amenities: ['Видеонаблюдение', 'Паркомати', 'Електрозарядка'], status: 'available'
    },
    {
        id: 10,
    name: 'До градски парк (ул. Стефан Стамболов)',
        location: 'ул. "Стефан Стамболов" 7',
        totalSpots: 110,
        availableSpots: 55,
        price: '3.80 BGN/час',
        rating: 4.3,
        reviews: 130,
        description: 'Удобен паркинг до големия градски парк.',
        coordinates: { lat: 42.5320, lng: 27.5050 },
        amenities: ['Охрана', 'Паркомати'], status: 'available'
    },
    {
        id: 11,
    name: 'Входна зона (магистрала)',
        location: 'при входа на града, автомагистрала А1',
        totalSpots: 300,
        availableSpots: 280,
        price: '2.00 BGN/час',
        rating: 3.9,
        reviews: 90,
        description: 'Голям бърз паркинг за пътуващи по магистралата.',
        coordinates: { lat: 42.5400, lng: 27.5200 },
        amenities: ['WC', 'Охрана'], status: 'available'
    },
    {
        id: 12,
    name: 'Mall Burgas (главен)',
        location: 'търговски център "Мол Бургас"',
        totalSpots: 500,
        availableSpots: 120,
        price: '4.00 BGN/час',
        rating: 4.4,
        reviews: 560,
        description: 'Паркинг на мола с много нива и ескалатори.',
        coordinates: { lat: 42.5450, lng: 27.5300 },
        amenities: ['Лифт', 'Паркомати', 'Достъп за инвалиди'], status: 'available'
    },
    {
        id: 13,
    name: 'Стадион (ул. Спортна)',
        location: 'ул. "Спортна" 1',
        totalSpots: 220,
        availableSpots: 80,
        price: '3.50 BGN/час',
        rating: 4.2,
        reviews: 300,
        description: 'Паркинг до стадиона, идеален за спортни събития.',
        coordinates: { lat: 42.5500, lng: 27.5400 },
        amenities: ['Охрана', 'Паркомати'], status: 'available'
    },
    {
        id: 14,
    name: 'Пристанищен терминал (зона)',
        location: 'при пристанищния терминал',
        totalSpots: 150,
        availableSpots: 60,
        price: '5.00 BGN/час',
        rating: 4.0,
        reviews: 210,
        description: 'Паркинг за пътуващи с фериботите.',
        coordinates: { lat: 42.5600, lng: 27.5500 },
        amenities: ['Охрана 24/7'], status: 'available'
    },
    {
        id: 15,
    name: 'Аерогара (зона)',
        location: 'между летището и терминал 2',
        totalSpots: 400,
        availableSpots: 350,
        price: '6.50 BGN/час',
        rating: 4.8,
        reviews: 800,
        description: 'Паркинг за авиационни пътници с шатъл до терминала.',
        coordinates: { lat: 42.5650, lng: 27.5600 },
        amenities: ['Шатъл', 'Зарядна станция', 'Охрана 24/7'], status: 'available'
    },
    {
        id: 16,
    name: 'Владая квартал',
        location: 'ж.к. "Владая"',
        totalSpots: 80,
        availableSpots: 20,
        price: '2.80 BGN/час',
        rating: 3.7,
        reviews: 65,
        description: 'Малък квартален паркинг, често пълен през вечерта.',
        coordinates: { lat: 42.5700, lng: 27.5700 },
        amenities: ['Паркомати'], status: 'full'
    },
    {
        id: 17,
    name: 'Стария град (улица)',
        location: 'улица "Стария град"',
        totalSpots: 60,
        availableSpots: 15,
        price: '3.20 BGN/час',
        rating: 4.3,
        reviews: 98,
        description: 'Романтичен паркинг в стария град, с каменни павета.',
        coordinates: { lat: 42.5750, lng: 27.5800 },
        amenities: ['Охрана'], status: 'available'
    },
    {
        id: 18,
    name: 'Технопарк (ул. Индустриална)',
        location: 'ул. "Индустриална" 40',
        totalSpots: 210,
        availableSpots: 180,
        price: '4.20 BGN/час',
        rating: 4.5,
        reviews: 420,
        description: 'Паркинг за служители в технологичната зона.',
        coordinates: { lat: 42.5800, lng: 27.5900 },
        amenities: ['Зарядна станция', 'Охрана'], status: 'available'
    },
    {
        id: 19,
    name: 'Университет (ул. Акад. Иван Гюзелев)',
        location: 'ул. "Акад. Иван Гюзелев"',
        totalSpots: 300,
        availableSpots: 60,
        price: '2.90 BGN/час',
        rating: 4.1,
        reviews: 360,
        description: 'Голям паркинг за студенти и преподаватели.',
        coordinates: { lat: 42.5850, lng: 27.6000 },
        amenities: ['Достъп за инвалиди', 'Паркомати'], status: 'available'
    },
    {
        id: 20,
    name: 'Младежки дом (Цар Симеон)',
        location: 'ул. "Цар Симеон" 10',
        totalSpots: 95,
        availableSpots: 25,
        price: '3.60 BGN/час',
        rating: 4.0,
        reviews: 145,
        description: 'Паркинг до младежкия дом и концертна зала.',
        coordinates: { lat: 42.5900, lng: 27.6100 },
        amenities: ['Охрана', 'Паркомати'], status: 'available'
    },
    {
        id: 21,
    name: 'Централна гара (около)',
        location: 'до централната жп гара',
        totalSpots: 180,
        availableSpots: 0,
        price: '3.80 BGN/час',
        rating: 3.6,
        reviews: 230,
        description: 'Шумен паркинг за пътуващи с влак.',
        coordinates: { lat: 42.5950, lng: 27.6200 },
        amenities: ['WC', 'Охрана'], status: 'full'
    },
    {
        id: 22,
    name: 'Кино Арена (около)',
        location: 'ул. "Кино Арена" 3',
        totalSpots: 120,
        availableSpots: 70,
        price: '4.10 BGN/час',
        rating: 4.2,
        reviews: 190,
        description: 'Паркинг до кино салона с нощно осветление.',
        coordinates: { lat: 42.6000, lng: 27.6300 },
        amenities: ['Охрана', 'Паркомати'], status: 'available'
    }
];

// Add curated real parkings for Izgrev, Slaveykov and Център (Burgas)
// Expand parkingData with many additional realistic parkings across Burgas
parkingData = [
    // existing curated central entries
    {
        id: 2001,
        name: 'Изгрев Център (ж.к. Изгрев)',
        location: 'ж.к. Изгрев',
        totalSpots: 140,
        availableSpots: 28,
        price: '3.50 BGN/час',
        rating: 4.2,
        reviews: 64,
        description: 'Паркинг в квартал Изгрев, близо до главните улици и удобен за бързи посещения.',
        coordinates: { lat: 42.5000, lng: 27.4670 },
        amenities: ['Паркомати', 'Охрана'], status: 'available'
    },
    {
        id: 2002,
        name: 'Изгрев Юг (жк. Изгрев)',
        location: 'ул. Изгрев',
        totalSpots: 80,
        availableSpots: 12,
        price: '3.00 BGN/час',
        rating: 4.0,
        reviews: 27,
        description: 'Малък паркинг за жители и посетители на района Изгрев.',
        coordinates: { lat: 42.4996, lng: 27.4680 },
        amenities: ['Камери'], status: 'available'
    },
    {
        id: 2003,
        name: 'Славейков Център',
        location: 'ул. Славейков / Център',
        totalSpots: 100,
        availableSpots: 9,
        price: '4.00 BGN/час',
        rating: 4.1,
        reviews: 48,
        description: 'Паркинг в зоната на Славейков — близо до магазини и заведения.',
        coordinates: { lat: 42.4985, lng: 27.4688 },
        amenities: ['Паркомати', 'Осветление'], status: 'available'
    },
    {
        id: 2004,
        name: 'Площад Славейков (краткосрочна зона)',
        location: 'площад Славейков',
        totalSpots: 60,
        availableSpots: 6,
        price: '3.80 BGN/час',
        rating: 3.9,
        reviews: 22,
        description: 'Малък обществен паркинг до площад Славейков.',
        coordinates: { lat: 42.4982, lng: 27.4696 },
        amenities: ['Осветление'], status: 'available'
    },
    {
        id: 2005,
        name: 'Площад Център (многоетажна зона)',
        location: 'Площад Център',
        totalSpots: 150,
        availableSpots: 18,
        price: '4.50 BGN/час',
        rating: 4.5,
        reviews: 180,
        description: 'Голям централен паркинг, удобен за всички административни и търговски обекти.',
        coordinates: { lat: 42.4977, lng: 27.4700 },
        amenities: ['Охрана 24/7', 'Паркомати'], status: 'available'
    },
    {
        id: 2006,
        name: 'Александровска (до пешеходната зона)',
        location: 'ул. Александровска',
        totalSpots: 90,
        availableSpots: 10,
        price: '4.00 BGN/час',
        rating: 4.2,
        reviews: 76,
        description: 'Паркинг близо до пешеходната зона и основните търговски улици.',
        coordinates: { lat: 42.4988, lng: 27.4682 },
        amenities: ['Камери', 'Достъп за инвалиди'], status: 'available'
    },

    // Additional realistic parkings across Burgas (3000+ series)
    {
        id: 3001,
        name: 'Морска градина - южна алея',
        location: 'Морска градина',
        totalSpots: 120,
        availableSpots: 25,
        price: '3.80 BGN/час',
        rating: 4.4,
        reviews: 140,
        description: 'Паркинг край Морската градина, удобно за плаж и разходки.',
        coordinates: { lat: 42.4980, lng: 27.4725 },
        amenities: ['Осветление', 'Паркомати'], status: 'available'
    },
    {
        id: 3002,
        name: 'Плато Богориди',
        location: 'бул. Богориди',
        totalSpots: 80,
        availableSpots: 8,
        price: '4.20 BGN/час',
        rating: 4.0,
        reviews: 50,
        description: 'Паркинг близо до крайбрежната алея и фестивалните пространства.',
        coordinates: { lat: 42.4968, lng: 27.4708 },
        amenities: ['Камери'], status: 'available'
    },
    {
        id: 3003,
        name: 'Централен пазар',
        location: 'Централен пазар',
        totalSpots: 100,
        availableSpots: 14,
        price: '3.20 BGN/час',
        rating: 4.1,
        reviews: 88,
        description: 'Паркинг до централния пазар за лесен достъп до търговските павилиони.',
        coordinates: { lat: 42.4993, lng: 27.4716 },
        amenities: ['Паркомати'], status: 'available'
    },
    {
        id: 3004,
        name: 'ЖП гара - зелена зона',
        location: 'Централна гара',
        totalSpots: 140,
        availableSpots: 10,
        price: '3.80 BGN/час',
        rating: 3.8,
        reviews: 110,
        description: 'Паркинг за пътуващи с влак, близо до гарата и автобусните спирки.',
        coordinates: { lat: 42.4958, lng: 27.4722 },
        amenities: ['WC', 'Осветление'], status: 'available'
    },
    {
        id: 3005,
        name: 'Морско Казино - подземна зона',
        location: 'бул. Богориди',
        totalSpots: 180,
        availableSpots: 30,
        price: '4.80 BGN/час',
        rating: 4.6,
        reviews: 210,
        description: 'Подземен паркинг в района на Морското казино и крайбрежието.',
        coordinates: { lat: 42.4971, lng: 27.4697 },
        amenities: ['Подземен', 'Охрана 24/7'], status: 'available'
    },
    {
        id: 3006,
        name: 'Площад Тройката - зона',
        location: 'Площад Тройката',
        totalSpots: 90,
        availableSpots: 5,
        price: '4.00 BGN/час',
        rating: 4.0,
        reviews: 75,
        description: 'Краткосрочен паркинг в непосредствена близост до централни обекти.',
        coordinates: { lat: 42.4975, lng: 27.4710 },
        amenities: ['Паркомати'], status: 'available'
    },
    {
        id: 3007,
        name: 'Парк "Егор"',
        location: 'ул. Славянска',
        totalSpots: 60,
        availableSpots: 20,
        price: '3.50 BGN/час',
        rating: 3.9,
        reviews: 34,
        description: 'Малък паркинг до зелените площи.',
        coordinates: { lat: 42.5150, lng: 27.4620 },
        amenities: ['Осветление'], status: 'available'
    },
    {
        id: 3008,
        name: 'Мол Бургас - допълнителна зона',
        location: 'Mall Burgas - допълнителна зона',
        totalSpots: 220,
        availableSpots: 60,
        price: '4.00 BGN/час',
        rating: 4.3,
        reviews: 320,
        description: 'Допълнителен паркинг за мола на отделно ниво.',
        coordinates: { lat: 42.5455, lng: 27.5310 },
        amenities: ['Паркомати', 'Лифт'], status: 'available'
    },
    {
        id: 3009,
        name: 'До Университетска библиотека',
        location: 'университетска зона',
        totalSpots: 110,
        availableSpots: 22,
        price: '3.00 BGN/час',
        rating: 4.1,
        reviews: 44,
        description: 'Паркинг близо до учебни корпуси и библиотека.',
        coordinates: { lat: 42.5830, lng: 27.5990 },
        amenities: ['Достъп за инвалиди'], status: 'available'
    },
    {
        id: 3010,
        name: 'Бургаска община - служебна зона',
        location: 'Община Бургас',
        totalSpots: 70,
        availableSpots: 6,
        price: '3.80 BGN/час',
        rating: 3.8,
        reviews: 28,
        description: 'Паркинг за административни посещения до общината.',
        coordinates: { lat: 42.4982, lng: 27.4722 },
        amenities: ['Охрана'], status: 'available'
    },
    {
        id: 3011,
        name: 'Платен краткосрочен - ул. "Богориди"',
        location: 'ул. Богориди',
        totalSpots: 50,
        availableSpots: 5,
        price: '4.50 BGN/час',
        rating: 3.9,
        reviews: 16,
        description: 'Краткосрочен паркинг близо до магазини и заведения.',
        coordinates: { lat: 42.4965, lng: 27.4710 },
        amenities: ['Паркомати'], status: 'available'
    },
    {
        id: 3012,
        name: 'Жил. "Слънце"',
        location: 'ж.к. Изгрев - малка площ',
        totalSpots: 40,
        availableSpots: 12,
        price: '2.80 BGN/час',
        rating: 3.7,
        reviews: 9,
        description: 'Квартален паркинг за жители.',
        coordinates: { lat: 42.5010, lng: 27.4665 },
        amenities: ['Осветление'], status: 'available'
    },
    {
        id: 3013,
        name: 'Експо център - временна зона',
        location: 'източна индустриална зона',
        totalSpots: 200,
        availableSpots: 120,
        price: '3.00 BGN/час',
        rating: 4.0,
        reviews: 48,
        description: 'Голям временен паркинг за събития и изложения.',
        coordinates: { lat: 42.5480, lng: 27.5200 },
        amenities: ['WC'], status: 'available'
    },
    {
        id: 3014,
        name: 'До детска градина "Рибка"',
        location: 'ж.к. Център - детска зона',
        totalSpots: 30,
        availableSpots: 8,
        price: '2.50 BGN/час',
        rating: 3.6,
        reviews: 12,
        description: 'Малък паркинг в близост до детски заведения.',
        coordinates: { lat: 42.4990, lng: 27.4690 },
        amenities: ['Осветление'], status: 'available'
    },
    {
        id: 3015,
        name: 'Търговска улица - подземна зона',
        location: 'централна търговска улица',
        totalSpots: 160,
        availableSpots: 24,
        price: '5.00 BGN/час',
        rating: 4.3,
        reviews: 95,
        description: 'Подземен паркинг под търговска улица в центъра.',
        coordinates: { lat: 42.4986, lng: 27.4694 },
        amenities: ['Подземен', 'Охрана'], status: 'available'
    }
];

// Persist the updated dataset and clear any OSM cache
try { localStorage.setItem('parkingData', JSON.stringify(parkingData)); } catch (e) { /* ignore */ }
try { localStorage.removeItem('osmNearbyParkings'); } catch (e) { /* ignore */ }

const newsData = [
    {
        id: 1,
        title: 'Нови камери в центъра на Бургас',
        description: 'Монтирани са високотехнологични камери за видеонаблюдение на паркингите в центъра.',
        date: '20 февруари 2026',
        icon: '📹'
    },
    {
        id: 2,
        title: 'Нова мобилна приложение',
        description: 'Стартира нова мобилна приложение за резервирани паркинги. Достъпна в iOS и Android.',
        date: '18 февруари 2026',
        icon: '📱'
    },
    {
        id: 3,
        title: 'Намаление на цени през лято',
        description: 'От юни до август ще има 20% отстъпка на всички паркингове.',
        date: '15 февруари 2026',
        icon: '🎉'
    },
    {
        id: 4,
        title: 'Паркинг "Панорама" рота е отворен',
        description: 'Новият луксозен паркинг с панорамна гледка привита съ специални тарифи.',
        date: '12 февруари 2026',
        icon: '🌟'
    },
    {
        id: 5,
        title: 'Электронни зарядни станции',
        description: 'Монтирани са 30 нови зарядни станции за електромобили по цел град.',
        date: '10 февруари 2026',
        icon: '⚡'
    },
    {
        id: 6,
        title: 'Нова топлина на паркингите',
        description: 'Открита е топлина с работно време в основните паркинги в града.',
        date: '08 февруари 2026',
        icon: '☕'
    },
    {
        id: 7,
        title: 'Кампания "Да водим отвоны"',
        description: 'Нова кампания за безопасна вождане по паркингите и понижение на стопови.',
        date: '05 февруари 2026',
        icon: '🚘'
    },
    {
        id: 8,
        title: 'ВиП оферта за старырски разсчети',
        description: 'Лица над 65-годишна възраст номурат вес отстъпки на всички паркинги.',
        date: '02 февруари 2026',
        icon: '🌟'
    },
    {
        id: 9,
        title: 'Паркинг "Новата гара" Финална фаза',
        description: 'Последните работи по отворению на новия модерен паркинг.',
        date: '28 януари 2026',
        icon: '🚧'
    },
    {
        id: 10,
        title: 'Юбилей АПМ 10 години',
        description: 'АПМ навърша 10 години сусъствуване и открива нови възможности.',
        date: '25 януари 2026',
        icon: '🎆'
    },
    {
        id: 11,
        title: 'Нови преди до ценыт ',
        description: 'На Васі диспозиция най-конкурентния айт за резервации паркомяста в Бургас.',
        date: '22 януари 2026',
        icon: '🏁'
    },
    {
        id: 12,
        title: 'Получи вашите ваучери',
        description: 'Любители на АПМ могат да желаю и да останбят в лобост до 30% вв година.',
        date: '20 януари 2026',
        icon: '🌟'
    }
];

const faqData = [
    {
        question: 'Как да тегля паркинг място?',
        answer: 'За да резервирате паркинг място, отворете страницата на паркинга, изберете желаното време и кликнете на бутона "Резервирай".'
    },
    {
        question: 'Какво се случва ако закаснея?',
        answer: 'Ако закаснеете, моля свържете се с нас поне 30 минути преди крайния час. Можем да продължим резервацията ако има свободни места.'
    },
    {
        question: 'Има ли гаранция за паркинга?',
        answer: 'Всички наши паркинги имат видеонаблюдение 24/7 и охрана. Осигурили сме максимална безопасност за вашия автомобил.'
    },
    {
        question: 'Как да отменя резервация?',
        answer: 'За отмяна на резервация, отворете страницата "Резервации" и кликнете на "Отмени" до резервацията, която искате да отмените.'
    },
    {
        question: 'Приемате ли кредитни карти?',
        answer: 'Да, приемаме всички основни кредитни карти, дебитни карти и цифрови портфейли.'
    },
    {
        question: 'Какъв е минималния период на резервация?',
        answer: 'Минималният период на резервация е 1 час. Максимално можете да резервирате до 7 дни предварително.'
    },
    {
        question: 'Мога ли да резервирам повече от един автомобил?',
        answer: 'Да, просто направете отделна резервация за всеки автомобил. Всеки ще получи собствено паркомясто.'
    },
    {
        question: 'Има ли отстъпки за дългосрочни резервации?',
        answer: 'За резервации над 24 часа, моля свържете се с нашата поддръжка за специални тарифи.'
    },
    {
        question: 'Какви са часовете на работа на паркингите?',
        answer: 'Повечето паркинги работят 24/7, но някои може да имат определени часове. Проверете подробностите на страницата на конкретния паркинг.'
    },
    {
        question: 'Мога ли да си върна парите при анулиране?',
        answer: 'Анулирането до 1 час преди началото на резервацията е безплатно. След това може да се приложат такси.'
    }
];